[package]
name = "rust_test_actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.5"
actix-rt = "2.6.0"
askama = "0.10.0"
serde = "1.0"
serde_derive = "1.0.110"
