# Use a Rust base image for building the application
FROM rust:latest as builder

# Set the working directory
WORKDIR /app

# Set proxy environment variables
ENV http_proxy=http://172.16.200.15:80
ENV https_proxy=http://172.16.200.15:80

# Copy the source code into the container
COPY . .
RUN ls ./ -la

# BUILD THE APPLICATION WITH OPTIMIZATIONS
RUN cargo build --release

# Command to start the Actix web server
CMD ["./target/release/rust_test_actix"]
