version: '3'
services:
  rust-app:
    image: rust:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["./target/release/rust_test_actix"]
    restart: always
    networks:
      - webnet
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./rust_app.conf:/etc/nginx/sites-available/rust_app.conf
#    depends_on:
#      - rust-app
#    networks:
#      - webnet
networks:
  webnet:
